common: &common
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_general_ci
  reconnect: true
  pool: 5
  socket: /var/lib/mysql/mysql.sock

development: &development
  <<: *common
  database: blog_samples_development
  username: root
  password:

test: &test
  <<: *common
  database: blog_samples_test
  username: root
  password:
